### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by mhsjlw** [mhsjlw/imdb#11]
Is this a feature that people would be interested in?

**Comment by Danwakeem** [comment]
I think that would be cool!

**Comment by mhsjlw** [comment]
What is the best way of going about this? Is there a module that can help us with this, or should we just persist to a Redis database?

**Comment by Danwakeem** [comment]
I have used [node-cache](https://www.npmjs.com/package/node-cache) in one of my projects before and it is easy enough to use. It also lets you configure it with Redis so we could add that as an option when initializing this api that way Redis wouldn't be a requirement for caching or anything?

I believe out of the box it will cache data in memory until the time you set for it is up.
