### ISSUE TITLE
No Access Control Allow Origin

### ISSUE THREAD

**Issue by mariosmaselli** [mhsjlw/imdb#14]
Hey, I just tried this...

```
//url is like this: http://www.imdb.com/title/tt0468569/

const url = e.target.href
const imdbRegex = new RegExp("tt\\d{7}", "g")
const imdbId = url.match( imdbRegex )

//console.log(imdbId[0]) I get the correct ID

imdb(imdbId[0], (err, data) => {
	if (err)
	    console.log(err.stack);

	if (data)
	     console.log(data);
});
```
Response:

Failed to load http://www.imdb.com/title/tt0468569/: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://mysite.dev' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Any idea what how can I fix this?

I have tried adding this on .htaccess but not working
`Header set Access-Control-Allow-Origin "*"
`

**Comment by mhsjlw** [comment]
IMDb does not allow you to access their site from a browser that has access restrictions enabled. The only way to get around this is to have a self hosted web API that wraps this module

**Comment by mhsjlw** [comment]
Going to close this
