### ISSUE TITLE
Integration with ebouther/imdb-id

### ISSUE THREAD

**Issue by ryanknutson** [mhsjlw/imdb#16]
Is there any way to integrate this with [ebouther/imdb-id](https://github.com/ebouther/imdb-id)?
I'm new at js so unfortunately I can't do this myself

**Comment by mhsjlw** [comment]
Well, that module returns the id, so you can run a search through there and then pipe that ID back into imdb. It looks like they'll work together just fine!

**Comment by ryanknutson** [comment]
Oh okay :) I'm just wondering though, will it take a performance hit? Both use cheerio and maybe the request could be simplified.

**Comment by mhsjlw** [comment]
It will not take a performance hit

**Comment by mhsjlw** [comment]
If we have the same dependency versions you will also not have to redownload the dependencies

**Comment by mhsjlw** [comment]
Simply install both modules

**Comment by ryanknutson** [comment]
Cool. Thanks!
